### ISSUE TITLE
Create Login Page / Setup

### ISSUE THREAD

**Issue by JakeGreer** [The-Music-Network/TMN-WEB#22]

**Comment by theRealScoobaSteve** [comment]
@JakeGreer Should this be a modal maybe for logging in? Theres already a issue for creating a landing page #14 IDK if you saw it

**Comment by JakeGreer** [comment]
@theRealScoobaSteve My mistake. I didnt realize home page and login were the same thing I was thinking homepage was going to be the main application page

**Comment by theRealScoobaSteve** [comment]
#14 Just going to reference this so you know to close/do this page as well, maybe make the login just a modal ? Idk up to you @JakeGreer
